### ISSUE TITLE
unknown Error

### ISSUE THREAD

**Issue by benx1n** [Tsuk1ko/CQ-picfinder-robot#22]
```
C:\Users\Administrator\.pm2\logs\cqpf-error.log last 15 lines:
0|cqpf     |       at IncomingMessage.EventEmitter.emit (domain.js:476:20)
0|cqpf     |       at endReadableNT (_stream_readable.js:1178:12)
0|cqpf     |       at processTicksAndRejections (internal/process/task_queues.js:80:21)
0|cqpf     |
0|cqpf     |
0|cqpf     |   Error: Request failed with status code 404
0|cqpf     |       at createError (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\axios\lib\core\createError.js:16:15)
0|cqpf     |       at settle (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\axios\lib\core\settle.js:17:12)
0|cqpf     |       at IncomingMessage.handleStreamEnd (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\axios\lib\adapters\http.js:237:11)
0|cqpf     |       at IncomingMessage.emit (events.js:214:15)
0|cqpf     |       at IncomingMessage.EventEmitter.emit (domain.js:476:20)
0|cqpf     |       at endReadableNT (_stream_readable.js:1178:12)
0|cqpf     |       at processTicksAndRejections (internal/process/task_queues.js:80:21)
0|cqpf     |
0|cqpf     | (node:2212) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

```
暂时未知结果
但服务器于上午出现了多次日志中已发送但群内未收到消息 重启pm2后解决

**平台**
   windows sever 2016
 - Node 版本：12.10.0

**Comment by Tsuk1ko** [comment]
这段日志只能体现是 axios 的实例创建错误，并没有涉及到具体的机器人代码或请求，而且根据你的描述这可能不属于机器人的 bug 🤔

**Comment by benx1n** [comment]
明白了  但是经常出现WS上已经post出去了，酷Q日志也有，但是没有收到消息 等复现了我看下日志Orz

**Comment by Tsuk1ko** [comment]
@benx1n 如果没有error，酷q日志有，实际上没发出去，一般是tx屏蔽了

这种现象一般出现在异地登录后的一段时间内，原因是新号或新地点登录在群里发言过多，某些色图被识别出来也可能发不出去

**Comment by benx1n** [comment]
嗯 今天凌晨的时候又出现了，只有私聊能得到回复 群聊完全没反应，连搜图的反馈都没
顺便请教下大佬= =绕过API调用限制的代理设置中 需要填协议格式吗？

**Comment by Tsuk1ko** [comment]
@benx1n 为了便利，仅 http
（上 https 不是自己找自己麻烦嘛）

当然，trace.moe 本身只能 https 所以是特殊判断使用 https 的

**Comment by benx1n** [comment]
connect ECONNREFUSED 127.0.0.1:80
at TCPConnectWrap.afterConnect [as oncomplete]
只能返回i.pximg.net长链，无法发送图片，且为两台服务器同时出现

**Comment by Tsuk1ko** [comment]
恢复了
