### ISSUE TITLE
反和谐反复报错

### ISSUE THREAD

**Issue by assassingyk** [Tsuk1ko/CQ-picfinder-robot#43]
之前使用的v2.11.0版本一直没有出现问题，今天更新之后使用setu功能时开始出现“反和谐发生错误，详情请看错误日志”的报错。

查看错误日志后发现问题都是Error: socket hang up 或者Error: Server responded with 500，但下面的信息都一样：

```
  Error: Request failed with status code 404
      at createError (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\createError.js:16:15)
      at settle (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\adapters\http.js:237:11)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

尝试搜索了下error 404的相关信息也没找到太多有价值的信息。报错本身基本是随机发生的，我在自己拉的小群里实验基本上每8到10张图会出现一次，没找到明显的规律所以不清楚复现条件……

**Comment by Tsuk1ko** [comment]
更新一下代码，错误的话应该会同时输出 URL，选几个把完整错误贴过来

**Comment by assassingyk** [comment]
好的，看了下错误基本分三类，我各选了一条贴过来
```
2020-1-18 1:30:27 [error] anti shielding
http://127.0.0.1:60233/?key=eekf3rnmv4b&url=https://i.pximg.net/img-master/img/2019/09/23/19/29/06/76932152_p0_master1200.jpg
Error: Server responded with 500

  Error: Request failed with status code 404
      at createError (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\createError.js:16:15)
      at settle (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\adapters\http.js:237:11)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

2020-1-18 1:34:16 [error] anti shielding
http://127.0.0.1:60233/?key=eekf3rnmv4b&url=https://i.pximg.net/img-master/img/2019/02/22/22/10/24/73329764_p0_master1200.jpg
Error: socket hang up

2020-1-18 1:40:06 [error] anti shielding
http://127.0.0.1:60233/?key=eekf3rnmv4b&url=https://i.pximg.net/img-master/img/2016/11/05/20/00/42/59812368_p0_master1200.jpg
Error: socket hang up
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Request failed with status code 400
    at createError (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Tsuk1ko** [comment]
第一个是因为作品被画师删了，我回头加个判断提示下

第二个第三个链接没问题，只能认定为网络不好……建议试一下配置`"pximgProxy": "https://i.pixiv.cat/"`

**Comment by assassingyk** [comment]
之前机器人是直接走的ssr代理所以就没有额外加反代，配置了https://i.pixiv.cat/的反代设置后404错误反而变多了，而且我直接去pixiv看原图几乎都是还在的，但是反代网址显示404 Not Found……是i.pixiv.cat那边出了问题？
总之我先用回自建本地反代了）

```
2020-1-18 20:03:13 [error] anti shielding
https://i.pixiv.cat/img-master/img/2019/02/11/23/04/44/73122922_p0_master1200.jpg
Error: Server responded with 404
[error] loadImage
Error: Server responded with 404
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\canvas\lib\image.js:56:28
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-concat\index.js:7:13)
    at Object.onceWrapper (events.js:299:28)
    at PassThrough.emit (events.js:210:5)
    at PassThrough.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

2020-1-18 20:06:15 [error] anti shielding
https://i.pixiv.cat/img-master/img/2019/02/14/15/48/47/73176125_p0_master1200.jpg
Error: Server responded with 404
[error] loadImage
Error: Server responded with 404
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\canvas\lib\image.js:56:28
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-concat\index.js:7:13)
    at Object.onceWrapper (events.js:299:28)
    at PassThrough.emit (events.js:210:5)
    at PassThrough.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

2020-1-18 20:06:37 [error] anti shielding
https://i.pixiv.cat/img-master/img/2019/02/04/01/37/56/72997025_p0_master1200.jpg
Error: Server responded with 404
[error] loadImage
Error: Server responded with 404
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\canvas\lib\image.js:56:28
    at C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (C:\Users\***\Documents\WindowsPowerShell\CQ-picfinder-robot\node_modules\simple-concat\index.js:7:13)
    at Object.onceWrapper (events.js:299:28)
    at PassThrough.emit (events.js:210:5)
    at PassThrough.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Tsuk1ko** [comment]
懂了，应该是因为我加到图库里之后作者修改了作品，导致 URL 里时间戳那部分变了，以前的 URL 自然就 404 了，我明天跑一遍更新应该就OK了

**Comment by Tsuk1ko** [comment]
> 懂了，应该是因为我加到图库里之后作者修改了作品，导致 URL 里时间戳那部分变了，以前的 URL 自然就 404 了，我明天跑一遍更新应该就OK了

更新完了，现在应该暂时不会有这种情况了

**Comment by assassingyk** [comment]
好的，目前暂时测试没有报错了。十分感谢
