### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by xenvocus** [Tsuk1ko/CQ-picfinder-robot#49]
**描述这个 bug**
更新部署之后使用命令npm start报错

**如何复现**
1. 启动酷Q及Http API 后在所在文件夹里启动命令行
2. 输入 npm start
3. 命令行内输出 ：
`2020-3-13 22:57:47 连接中[/event]#1
2020-3-13 22:57:47 连接中[/api]#1
2020-3-13 22:57:47 连接成功[/event]
2020-3-13 22:57:47 连接成功[/api]#1`
4. 输出下面日志中的内容
5.之后停止输出内容，但通过聊天仍能正常使用

**期望现象**
命令行内正常输出内容

**截图及日志**
- 问题相关截图
![20200313230651](https://user-images.githubusercontent.com/56790256/76633440-add6aa00-657f-11ea-9b46-c3f826cacf16.png)
`You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Request failed with status code 404
    at createError (C:\Users\Administrator\Downloads\CQ-picfinder-robot\node_modules\_axios@0.19.2@axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Administrator\Downloads\CQ-picfinder-robot\node_modules\_axios@0.19.2@axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Administrator\Downloads\CQ-picfinder-robot\node_modules\_axios@0.19.2@axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
`

**平台**
 - 操作系统： Windows Server 2012 64-bit中文版
 - Node 版本：12.13.0

**附加内容**
似乎不影响使用的样子？但这是什么原因呢qwq？

**Comment by Tsuk1ko** [comment]
应该修复了，更新一下代码然后重启程序即可

**Comment by xenvocus** [comment]
> 应该修复了，更新一下代码然后重启程序即可

已经没有问题了，非常感谢大佬！
