### ISSUE TITLE
websocket连接失败

### ISSUE THREAD

**Issue by himesamanoyume** [Tsuk1ko/CQ-picfinder-robot#50]
**描述这个 bug**
log中websocket连接错误，用air版在群聊@+图片时，能回复不带图的正常消息，用pro版在群聊@+图片时，没有任何回应。但是pro版私聊中可以正常回复带图片的消息，总之pro版群聊中一切搜图行为都不能实现，air版因为不带图片所有搜图都可以回复。

**如何复现**

**期望现象**
群聊中@+图片能回复带图片的正常消息

**截图及日志**
```
2020-3-14 14:29:14 连接错误[/api]
{ SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\cq-websocket\src\index.js:451:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\_yaeti@0.0.6@yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\_websocket@1.0.31@websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\_websocket@1.0.31@websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:197:13)
    at WebSocketClient.EventEmitter.emit (domain.js:446:20)
    at ClientRequest.handleRequestError (C:\Users\Administrator\Desktop\CQ-picfinder-robot-master\node_modules\_websocket@1.0.31@websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:197:13)
    at ClientRequest.EventEmitter.emit (domain.js:446:20)
    at Socket.socketErrorListener (_http_client.js:397:9) name: 'SocketError' }
```

**平台**
 - 操作系统：Windows 10
 - Node 版本：6.7.0

**附加内容**

**Comment by himesamanoyume** [comment]
```
2020-3-14 15:09:47 [error] saucenao[0][request]
{ Error: getaddrinfo EAI_AGAIN saucenao.com saucenao.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'saucenao.com',
  host: 'saucenao.com',
  port: 443,
  config:
   { url: 'https://saucenao.com/search.php',
     method: 'get',
     params:
      { db: 999,
        output_type: 2,
        numres: 3,
        url:
         'https://c2cpicdw.qpic.cn/offpic_new/285835609//9cad4a35-150e-4f8e-84ee-8851eea0f42a/0?term=2' },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      [Object: null prototype] {
        response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'https:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path:
         '/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F285835609%2F%2F9cad4a35-150e-4f8e-84ee-8851eea0f42a%2F0%3Fterm%3D2',
        method: 'GET',
        headers: [Object],
        agent: undefined,
        agents: [Object],
        auth: undefined,
        hostname: 'saucenao.com',
        port: null,
        nativeProtocols: [Object],
        pathname: '/search.php',
        search:
         '?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F285835609%2F%2F9cad4a35-150e-4f8e-84ee-8851eea0f42a%2F0%3Fterm%3D2' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F285835609%2F%2F9cad4a35-150e-4f8e-84ee-8851eea0f42a%2F0%3Fterm%3D2 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36\r\nHost: saucenao.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F285835609%2F%2F9cad4a35-150e-4f8e-84ee-8851eea0f42a%2F0%3Fterm%3D2',
        _ended: false,
        res: null,
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl:
      'https://saucenao.com/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F285835609%2F%2F9cad4a35-150e-4f8e-84ee-8851eea0f42a%2F0%3Fterm%3D2' },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function] }
```

**Comment by Tsuk1ko** [comment]
1. 群聊没反应请阅读 wiki [常见问题](https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
2. api 连接错误理应与这一问题无关，因为连不上的话必发不了言，这可能是你以前出错误时的错误日志
3. saucenao 错误里写着`getaddrinfo`错误说明是域名解析失败，如果不是偶发现象，请检查你的 DNS

**Comment by himesamanoyume** [comment]
我把npm更新到最新版就解决了....
