### ISSUE TITLE
运行时出现无法连接

### ISSUE THREAD

**Issue by Edward945** [Tsuk1ko/CQ-picfinder-robot#57]
**描述这个 bug**
运行时出现无法连接

**如何复现**
复现步骤（如果能复现）
1. 照https://www.moerats.com/archives/953/ 进行安装
2. npm run pm2log

**截图及日志**
```
0|CQPF  | 4/25/2020, 1:10:34 AM 连接错误[/event]
0|CQPF  | { SocketError: Failed to establish the websocket connection.
0|CQPF  |     at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/cq-websocket/src/index.js:451:70)
0|CQPF  |     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/yaeti/lib/EventTarget.js:115:12)
0|CQPF  |     at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
0|CQPF  |     at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
0|CQPF  |     at WebSocketClient.emit (events.js:198:13)
0|CQPF  |     at WebSocketClient.EventEmitter.emit (domain.js:448:20)
0|CQPF  |     at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/websocket/lib/WebSocketClient.js:227:14)
0|CQPF  |     at ClientRequest.emit (events.js:198:13)
0|CQPF  |     at ClientRequest.EventEmitter.emit (domain.js:448:20)
0|CQPF  |     at Socket.socketErrorListener (_http_client.js:401:9) name: 'SocketError' }
0|CQPF  | 4/25/2020, 1:10:34 AM 连接失败[/event]#24
```

**平台**
 - 操作系统：Debian 9
 - Node 版本：v10.20.1
 - Npm 版本：6.14.4

**Comment by Tsuk1ko** [comment]
若不清楚连接细节建议使用 win 服务器
