### ISSUE TITLE
图片标题带有emoji时会在数据库写入缓存时引发异常

### ISSUE THREAD

**Issue by CiaranZhou** [Tsuk1ko/CQ-picfinder-robot#74]
1. Bug 描述
   - 图片标题带有emoji的话，缓存不会写入数据库且报错
   - 正常情况下不会有报错，且图片相关信息正常写入数据库
2. 日志和配置
   - 生成的错误日志如下
```
0|CQPF     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|CQPF     | Error: Incorrect string value: '\xF0\x9F\x8C\xB8\xE3\x80...' for column 'msg' at row 1
0|CQPF     |     at Packet.asError (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/packets/packet.js:497:13)
0|CQPF     |     at Query.Command.execute (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/commands/command.js:25:22)
0|CQPF     |     at Connection.handlePacket (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/connection.js:310:28)
0|CQPF     |     at PacketParser.onPacket (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/connection.js:83:65)
0|CQPF     |     at PacketParser.executeStart (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/packet_parser.js:39:12)
0|CQPF     |     at Socket.<anonymous> (/root/CQ-picfinder-robot/node_modules/_mysql2@0.15.8@mysql2/lib/connection.js:95:31)
0|CQPF     |     at Socket.emit (events.js:198:13)
0|CQPF     |     at Socket.EventEmitter.emit (domain.js:448:20)
0|CQPF     |     at addChunk (_stream_readable.js:288:12)
0|CQPF     |     at readableAddChunk (_stream_readable.js:269:11)
```
数据库字符集确定是utf8mb4

3. 运行环境
   - 系统：Ubuntu16.04
   - Node 版本： v10.21.0

**Comment by Tsuk1ko** [comment]
直接使用 sqlite 是否有这种情况？

**Comment by CiaranZhou** [comment]
> 直接使用 sqlite 是否有这种情况？

sqlite使用正常，只有配置使用mysql会出现

**Comment by Tsuk1ko** [comment]
那直接使用 sqlite 吧，mysql 是计划要废弃的，说实话用 mysql 占用这么多资源做这点小小的缓存意义不大

**Comment by Tsuk1ko** [comment]
不过按理来说 utf8mb4 也应该能正常存 emoji 才对🤔
