### ISSUE TITLE
setu服务器爆炸

### ISSUE THREAD

**Issue by Annabel0530** [Tsuk1ko/CQ-picfinder-robot#8]
以前也很少有出现 但很快就自行解决了
现在情况持续了两天 试过修改pximgProxy参数仍无法解决
人在国内 是否需要代理？

**Comment by Tsuk1ko** [comment]
@Annabel0530 我想起来因为我这个 api 所在的服务器被墙了……

我一会去搬到没被墙的服务器上

**Comment by Tsuk1ko** [comment]
@Annabel0530 已完成迁移，目前应该正常了

**Comment by miyouzi** [comment]
@Tsuk1ko 现在又发生了这个问题，使用```proxy```参数代理及```"pximgProxy": "https://i.pixiv.cat/"```均不能解决问题，Log如下：

```
2019-9-15 09:40:09 连接错误[/api]
{ SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (D:\picfinder\CQ-picfinder-robot\node_modules\cq-websocket\src\index.js:451:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (D:\picfinder\CQ-picfinder-robot\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (D:\picfinder\CQ-picfinder-robot\node_modules\websocket\lib\W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (D:\picfinder\CQ-picfinder-robot\node_modules\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:189:13)
    at WebSocketClient.EventEmitter.emit (domain.js:441:20)
    at ClientRequest.handleRequestError (D:\picfinder\CQ-picfinder-robot\node_modules\websocket\lib\WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at Socket.socketErrorListener (_http_client.js:392:9) name: 'SocketError' }
2019-9-15 09:40:31
TypeError: Cannot read property '0' of null
2019-9-15 09:42:30
TypeError: Cannot read property '0' of null
2019-9-15 09:42:30
TypeError: Cannot read property '0' of null
```

**Comment by Tsuk1ko** [comment]
@miyouzi 恢复了
